apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: accounts-service
  type: ClusterIP